### ISSUE TITLE
Generic Methods with two generic paramters

### ISSUE THREAD

**Issue by wiewiur25** [TNG/ArchUnitNET#46]
Hello!

I found bug probably. When I tried Build Architecture using ArchLoader with Build method I have exception:

`System.InvalidOperationException : Full name of declaring member doesn't match.
   at ArchUnitNET.Domain.GenericParameter.AssignDeclarer(IMember declaringMethod)
   at ArchUnitNET.Loader.LoadTasks.AddGenericParameterDependencies.AddMemberGenericParameterDependencies()
   at ArchUnitNET.Loader.LoadTasks.AddGenericParameterDependencies.Execute()
   at ArchUnitNET.Loader.LoadTaskRegistry.<ExecuteTasks>b__1_1(Type taskKey)
   at ArchUnitNET.Domain.Extensions.EnumerableExtensions.ForEach[T](IEnumerable`1 source, Action`1 action)
   at ArchUnitNET.Loader.LoadTaskRegistry.ExecuteTasks(List`1 taskOrder)
   at ArchUnitNET.Loader.ArchBuilder.UpdateTypeDefinitions()
   at ArchUnitNET.Loader.ArchBuilder.Build()
   at ArchUnitNET.Loader.ArchLoader.Build()`

I little investigated it and I think the proble is with overloaded generic methods. See screenshots. 

How can I handle with this case? Should wait for fix, or you have some workaround how can I build architecture with generic overloaded methods.

thank you in advance!

Have a good day!
![test](https://user-images.githubusercontent.com/7118305/106133491-9daec580-6165-11eb-8ba5-8a6618e57747.JPG)

**Comment by fgathercoupa** [comment]
Hi @wiewiur25 , 
thanks for letting us know. This looks like a bug and we are currently looking into it. 

Best Regards

**Comment by wiewiur25** [comment]
It isn't urgent. I realized I dont need whole assembly, I can use LoadNamespacesWithinAssembly and it is ok for me.

**Comment by brandhuf** [comment]
PR #47 should fix this issue

**Comment by fgather** [comment]
@wiewiur25 , I just released version 0.4.3, which should appear on nuget soon and hopefully fix it.

**Comment by wiewiur25** [comment]
thanks, now It's working!
