### ISSUE TITLE
LoadAssembliesIncludingDependencies fails for record type

### ISSUE THREAD

**Issue by mw-ste** [TNG/ArchUnitNET#76]
Hi, I have a problem when using the `LoadAssembliesIncludingDependencies` method with the `record` types introduced in C#9.
The problem occured when migrating old classes to record types. 
Suddenly I was getting `NullReferenceException`s in my unit tests (stacktrace at the end of the issue).

I tried to narrow it down and the trigger for the exception seems to be a method inside my new `record` type:
```csharp
public ProductIdentityBase CopyWithNewName(string name)
{
    return this with { Name = name };
}
```

I wanted to keep the old method signatures for creating copies of my classes.

I created a **minimal example** in my github to reproduce the issue, feel free to check it out:
https://github.com/mw-ste/ArchUnitNetRecordTypes

**Stack trace:**
```
System.NullReferenceException
Object reference not set to an instance of an object.
   at ArchUnitNET.Loader.LoadTasks.AddMethodDependencies.CreateMethodBodyDependenciesRecursive(MethodBody methodBody, ICollection`1 visitedMethodReferences, List`1 bodyTypes, List`1 castTypes, List`1 typeCheckTypes, List`1 metaDataTypes, List`1 accessedFieldMembers)+MoveNext()
   at ArchUnitNET.Loader.LoadTasks.AddMethodDependencies.CreateMethodBodyDependenciesRecursive(MethodBody methodBody, ICollection`1 visitedMethodReferences, List`1 bodyTypes, List`1 castTypes, List`1 typeCheckTypes, List`1 metaDataTypes, List`1 accessedFieldMembers)+MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.DistinctIterator`1.MoveNext()
   at ArchUnitNET.Loader.LoadTasks.AddMethodDependencies.CreateMethodBodyDependencies(MethodDefinition methodDefinition, MethodMember methodMember)+MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at ArchUnitNET.Loader.LoadTasks.AddMethodDependencies.<>c.<Execute>b__4_3(ValueTuple`2 tuple)
   at ArchUnitNET.Domain.Extensions.EnumerableExtensions.ForEach[T](IEnumerable`1 source, Action`1 action)
   at ArchUnitNET.Loader.LoadTasks.AddMethodDependencies.Execute()
   at ArchUnitNET.Loader.LoadTaskRegistry.<ExecuteTasks>b__1_1(Type taskKey)
   at ArchUnitNET.Domain.Extensions.EnumerableExtensions.ForEach[T](IEnumerable`1 source, Action`1 action)
   at ArchUnitNET.Loader.LoadTaskRegistry.ExecuteTasks(List`1 taskOrder)
   at ArchUnitNET.Loader.ArchBuilder.UpdateTypeDefinitions()
   at ArchUnitNET.Loader.ArchBuilder.Build()
   at ArchUnitNET.Loader.ArchLoader.Build()
   at ArchUnitNetRecordTypes.Should.ArchUnitNetRecordShould.WorkWithRecordTypes() in E:\ArchUnitNetRecordTypes\ArchUnitNetRecordTypes.Should\ArchUnitNetRecordShould.cs:line 13
```

**Comment by mw-ste** [comment]
I played around a little bit and came up with a possible fix, or at least workaround.

In the method `CreateMethodBodyDependenciesRecursive` of the class `AddMethodDependencies` I replaced the line:
```csharp
if (calledMethodDefinition == null)
``` 
with the line:
```csharp
if (calledMethodDefinition?.Body == null)
```

I didn't create a PR, because I would have to update several projects to .Net 5 to create a proper test for a `record` type... 
Also I don't really know what's going on 😃

**Comment by mw-ste** [comment]
Thanks for taking care of that so quickly 👍

**Comment by mw-ste** [comment]
No problem, it's not urgent ;)
